storageAccounts:
    - name: cloudarchive01
      provider: azure
      key1: (C:\_CERT\AZURE_KEY.txt)
      key2: azure only uses key 1
        
    - name: cloudarchive02
      provider: s3
      key1: (c:\_CERT\S3_ACCESS_KEY_ID.txt)
      key2: (c:\_CERT\S3_SHARED_ACCESS_KEY.txt)
  
areas:
  - name: book_images
    folder: C:\_BOOK
    container: books
    remoteBranch: images
    storage: cloudarchive01
    fileTypes:
        - extension: png
        - extension: svg
        - extension: jpg
        - extension: jpeg
        - extension: gif
          
  - name: book_text
    folder: C:\_BOOK
    container: books
    remoteBranch: text
    storage: cloudarchive01
    fileTypes:
        - extension: txt
  
  - name: mp3
    folder: C:\_AUDIOTEST
    container: mp3
    storage: cloudarchive01
    fileTypes:
        - extension: mp3
       
  - name: archives
    remoteBranch: misc
    container: s3 does not use container; use remoteBranch for a remote folder
    folder: C:\_ARCHIVETEST
    storage: cloudarchive02
    fileTypes:
        - extension: zip
        - extension: rar
        - extension: gz